extends: airbnb-base
# plugins:
#   - import
rules:
  arrow-body-style:
    - error
    - always
  array-callback-return: 
    - error
  camelcase: ["error", { properties: "never" }]
  class-methods-use-this: 0
  comma-dangle:
    - error
    - arrays: only-multiline
      objects: only-multiline
      functions: never
  eol-last:
    - error
    - windows
  indent:
    - error
#    - tab #4
  init-declarations: "off"
  linebreak-style:
    - error
    - windows
  max-len: 
    - error
    - 200
  no-cond-assign:
    - error
    - always
  no-console: "off"
  no-empty: warn
  no-inline-comments: "off"
  no-multi-str: 0
  no-param-reassign: 
    - error 
    - props: false
  no-underscore-dangle: 0
  no-use-before-define: 
    - error
    - functions: false
      classes: true
      variables: false
  object-shorthand: 
    - error
    - never
  one-var: "off" # ["error", "never"]
