session:
  #  Session expiration in miliseconds
  expiration: '1 day'

siscom:
  base_url: #???
  encryption_key: #???
  encryption_algorithm: aes-256-cbc

enable_new_relic: true

week_days:
  - Dom
  - Seg
  - Ter
  - Qua
  - Qui
  - Sex
  - Sab

api_docs:
  route: /docs
  target_path: public

log:
  rotation:
    keep: 5
    size: 100m
  timestamp: true
  json: false
  colorize: true
  level: debug
  app:
    path:
      debug: C:/Projetos/Engagement/logs/backend/bancas_app.log
      error: C:/Projetos/Engagement/logs/backend/bancas_app_err.log
  elastic:
    path:
      debug: C:/Projetos/Engagement/logs/backend/bancas_elastic.log
      error: C:/Projetos/Engagement/logs/backend/bancas_elastic_err.log

morgan: combined

integracao:
  connectionString: "???"
  queueName: "produtobanca"

group:
  upload:
    id: #???
  affiliate: [AVynCaHP0r3lkoFo1x7K, AWF14pFxE50PSDSmK-p-]

# Elasticsearch configurations
elasticsearch:
  hosts:
    - https://???
  index: banca
  users:
    index: siscom_users
    type: siscomUsers
  groups: 
    index: siscom_users
    type: groups
  activity:
    index: banca
    type: activities

permission:
  digital_media_group: "digital_media"

aws:
  accessKeyId: #??? 
  secretAccessKey: #???
  region: us-east-1
  s3: https://s3.amazonaws.com

# Attachments configuration (S3)
attachments:
  bucket: bancaprojetos-attachments-h

# Push notifications configurations
notifications:
  broadcast_topic: arn:???:banca-homolog
  application: arn:???:app/APNS/banca-homolog 
  region: us-east-1

  msg_templates:
    create: Plano <%= name %> está disponível para venda.
    update: Plano <%= name %> foi modificado.

scheduling:
  queue: redis://127.0.0.1:6379
  jobs:
    - name: Users
      handler: dump_users
      data:
        API_DUMP_HOSTNAME: #???
        API_FULL_DUMP_USERS_ENDPOINT: /ComercialApps.Apresentacao/api/v1/siscom-users
        DI_APIKEY: #???
      options:
        jobId: user_dump
        repeat:
          cron: '*/30 * * * *'
    - name: Plans
      handler: dump_plans
      data:
        API_DUMP_HOSTNAME: #???
        API_FULL_DUMP_ENDPOINT: /ComercialApps.Apresentacao/api/v1/plans/full
        DI_APIKEY: #???
      options:
        jobId: plans_dump
        repeat:
          cron: '*/30 * * * *'

mobile:
  bucket: homolog

dynamo:
  enviroment: hml

crmGo:
  # OAuth Token Endpoint
  authorityUrl: https://login.microsoftonline.com/???/oauth2/token
  tipoPessoaCliente: 5145C4C0-7FA9-4D5D-94BA-A4ABB5C8E1F1
  tipoPessoaAgencia: 7D62A70A-029C-42D8-A617-8ED5168E0D02
  # CRM Organization URL
  resource: https://homolog.crm.dynamics.com
  webApiUrl: https://homolog.api.crm.dynamics.com/api/data/v8.2/
  # Dynamics 365 Client Id when registered in Azure - HML
  clientId: #???
  clientSecret: #???
  impersonate: 681B5FD9-0BB5-4D8E-96E7-8DBFD9F17477 # usuário = Lucas - HML
  currency: 0f5684cd-fc2a-e711-8105-c4346bb59890 # moeda = Real - HML
  uoms: d84a42ad-56a6-4196-892f-556422b407d2 # unidade de medida principal - HML
  pricelevelId: A0741EE0-FDA9-E711-810F-E0071B714BD1 # lista de preços padrão - HML
