session:
  #  Session expiration in miliseconds
  expiration: 1 day

siscom:
  base_url: #???
  encryption_key: #???
  encryption_algorithm: aes-256-cbc

enable_new_relic: true

api_docs:
  route: /docs
  target_path: public

log:
  rotation:
    keep: 5
    size: 100m
  timestamp: true
  json: false
  colorize: true
  level: debug
  app:
    path:
      debug: C:/Projetos/Engagement/logs/backend/bancas_app.log
      error: C:/Projetos/Engagement/logs/backend/bancas_app_err.log
  elastic:
    path:
      debug: C:/Projetos/Engagement/logs/backend/bancas_elastic.log
      error: C:/Projetos/Engagement/logs/backend/bancas_elastic_err.log

morgan: common

integracao:
  connectionString: #???
  queueName: "produtobanca"

week_days:
  - dom
  - seg
  - ter
  - qua
  - qui
  - sex
  - sab

# Elasticsearch configurations
elasticsearch:
  hosts:
    - search-???
  index: banca
  users:
    index: siscom_users
    type: siscomUsers
  groups:
    index: siscom_users
    type: groups
  activity:                                                                                          
    index: banca
    type: activities
  projeto:
      index: projetos 

permission:
  digital_media_group: digital_media

aws:
  accessKeyId: #???
  secretAccessKey: #???
  region: us-east-1
  s3: https://s3.amazonaws.com

# Attachments configuration (S3)
attachments:
  bucket: arquivos.banca

notifications:
  broadcast_topic: arn:???:banca-prod
  application: arn:???:app/APNS/banca-prod
  region: us-east-1

  msg_templates:
    create: Plano <%= name %> disponível para venda.
    update: Plano <%= name %> foi modificado, consulte o campo descrição

scheduling:
  queue: redis://127.0.0.1:6379
  jobs:
    - name: Users
      handler: dump_users
      data:
        API_DUMP_HOSTNAME: #???
        API_FULL_DUMP_USERS_ENDPOINT: /ComercialApps.Apresentacao/api/v1/siscom-users
        DI_APIKEY: #???
      options:
        jobId: user_dump
        repeat:
          cron: '*/30 * * * *'
    - name: Plans
      handler: dump_plans
      data:
        API_DUMP_HOSTNAME: #???
        API_FULL_DUMP_ENDPOINT: /ComercialApps.Apresentacao/api/v1/plans/full
        DI_APIKEY: #???
      options:
        jobId: plans_dump
        repeat:
          cron: '*/30 * * * *'

mobile:
  bucket: bancaprojetos-prod

dynamo:
  enviroment: prd

crmGo:
  # OAuth Token Endpoint
  authorityUrl: https://login.microsoftonline.com/???/oauth2/token
  tipoPessoaCliente: 5145C4C0-7FA9-4D5D-94BA-A4ABB5C8E1F1
  tipoPessoaAgencia: 7D62A70A-029C-42D8-A617-8ED5168E0D02
  # CRM Organization URL
  resource: https://crm2.dynamics.com
  webApiUrl: https://api.crm2.dynamics.com/api/data/v8.2/
  # Dynamics 365 Client Id when registered in Azure - PRD
  clientId: #??? # Id do aplicativo
  clientSecret: #??? # chave
  impersonate: e1fce234-a4e1-4fef-b92b-db411253f414 # usuário = Joaquim
  currency: FFAF1A44-675D-E711-80FE-E0071B68C9A1 # moeda = Real
  uoms: 0E78E946-6093-434B-A7D7-FD7FB7F01F5C # unidade de medida principal
  pricelevelId: A0741EE0-FDA9-E711-810F-E0071B714BD1 # lista de preços padrão
